#! /usr/bin/env python
"""
The Aegean source finding program.

"""

from __future__ import annotations

import sys

from AegeanTools.CLI import aegean

if __name__ == "__main__":
    sys.exit(aegean.main(sys.argv[1:]))
