#! /usr/bin/env python
"""
 Tool for making residual images with Aegean tables as input
"""

import sys

from AegeanTools.CLI import AeRes

if __name__ == "__main__":
    sys.exit(AeRes.main(sys.argv[1:]))
