#! /usr/bin/env python
"""
A regrouping tool to accompany the Aegean source finding program.
"""

from __future__ import annotations

import sys

from AegeanTools.CLI import AeReg

if __name__ == "__main__":
    sys.exit(AeReg.main(sys.argv[1:]))
