#! /usr/bin/env python
"""
MIMAS - The Multi-resolution Image Mask for Aegean Software

Created: Paul Hancock, Oct 2014

TODO: Write an in/out reader for MOC formats described by
http://arxiv.org/abs/1505.02937

"""
import sys

from AegeanTools.CLI import MIMAS

if __name__ == "__main__":
    sys.exit(MIMAS.main(sys.argv[1:]))
