#! /usr/bin/env python
"""
A regrouping tool to accompany the Aegean source finding program.
"""

from AegeanTools.cluster import regroup
from AegeanTools.catalogs import save_catalog, load_table, table_to_source_list

import numpy as np

import logging
import argparse
import sys
import os

__author__ = ['PaulHancock']
__date__ = '2021-09-03'
__version__ = '0.1-alpha'


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog='regroup', prefix_chars='-')
    group1 = parser.add_argument_group("Required")
    group1.add_argument('--input', dest='input', type=str, default=None, required=True,
                        help='The input catalogue.')
    group1.add_argument("--table", dest='tables', default=None, type=str, required=True,
                        help="Table outputs, format inferred from extension.")

    group2 = parser.add_argument_group("Optional")
    group2.add_argument('--ratio', dest='ratio', default=None, type=float,
                        help="The ratio of synthesized beam sizes (image psf / input catalog psf). ")
    group2.add_argument('--debug', dest='debug', action='store_true', default=False,
                        help="Debug mode.")

    options = parser.parse_args()

    if options.input is None:
        parser.print_usage()
        sys.exit()

    invocation_string = " ".join(sys.argv[:])

    # configure logging
    logging_level = logging.DEBUG if options.debug else logging.INFO
    log = logging.getLogger("Aegean")
    logging.basicConfig(level=logging_level, format="%(process)d:%(levelname)s %(message)s")
    log.info("This is regroup {0}-({1})".format(__version__, __date__))
    log.debug("Run as:\n{0}".format(invocation_string))

    # check that a valid intput filename was entered
    filename = options.input
    if not os.path.exists(filename):
        log.error("{0} not found".format(filename))
        sys.exit(1)
    
    input_table = load_table(options.input)
    input_sources = np.array(table_to_source_list(input_table))

    sources = input_sources
    
    if options.tables:
        meta = {"PROGRAM": "regroup",
                "PROGVER": "{0}-({1})".format(__version__, __date__),
                "CATFILE": filename,
                "RUN-AS": invocation_string}
        for t in options.tables.split(','):
            save_catalog(t, sources, meta=meta)
    sys.exit()