#! /usr/bin/env python
"""
A regrouping tool to accompany the Aegean source finding program.
"""

from AegeanTools.cluster import regroup

import logging
import argparse
import sys
import os

__author__ = ['PaulHancock']
__date__ = '2021-09-03'
__version__ = '0.1-alpha'


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog='regroup', prefix_chars='-')
    parser.add_argument('--input', dest='input', type=str, default=None,
                        help='The input catalogue.')
    parser.add_argument("--table", dest='tables', default=None, type=str,
                        help="Additional table outputs, format inferred from extension. [default: none]")
    parser.add_argument('--ratio', dest='ratio', default=None, type=float,
                        help="The ratio of synthesized beam sizes (image psf / input catalog psf). ")
    parser.add_argument('--debug', dest='debug', action='store_true', default=False,
                        help="Debug mode.")

    options = parser.parse_args()

    if options.input is None:
        parser.print_help()
        sys.exit()

    invocation_string = " ".join(sys.argv[:])

    # configure logging
    logging_level = logging.DEBUG if options.debug else logging.INFO
    log = logging.getLogger("Aegean")
    logging.basicConfig(level=logging_level, format="%(process)d:%(levelname)s %(message)s")
    log.info("This is regroup {0}-({1})".format(__version__, __date__))
    log.debug("Run as:\n{0}".format(invocation_string))

    # check that a valid intput filename was entered
    filename = options.input
    if not os.path.exists(filename):
        log.error("{0} not found".format(filename))
        sys.exit(1)
    