#! /usr/bin/env python
"""
A program to provide a command line interface to the
AegeanTools.fits_tools module
"""

import sys

from AegeanTools.CLI import SR6

if __name__ == "__main__":
    sys.exit(SR6.main(sys.argv[1:]))
